# fly.toml app configuration file generated for logan on 2023-06-08T10:35:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "logan"
primary_region = "cdg"

[http_service]
  internal_port = 4999
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
